
package main;

import com.sun.glass.events.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 * Yazilim Laboratuvari I Proje 1
 * @author Oguz Aktas
 */
public class AdminLoginWindow extends javax.swing.JFrame {
    
    /**
     * Creates new form AdminLoginWindow
     */
    public AdminLoginWindow() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Kitap Okuma ve Oneri Sistemi");
    }
    
    public Connection getConnection() throws SQLException, ClassNotFoundException {
        Connection conn;
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/book_crossing?useSSL=false", "root", "123456");
            return conn;
        } catch (SQLException ex) {
            Logger.getLogger(AdminLoginWindow.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "<html><b>Veritabanina baglanti saglanamadi</b></html>");
        }
        return null;
    }
    
    public boolean checkInputs() {
        if (text_username.getText().trim().isEmpty() || password.getText().trim().isEmpty()) {
            return false;
        } else {
            return true;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        label_username = new javax.swing.JLabel();
        text_username = new javax.swing.JTextField();
        label_password = new javax.swing.JLabel();
        Btn_Menu = new javax.swing.JButton();
        password = new javax.swing.JPasswordField();
        Btn_Giris = new javax.swing.JButton();
        label_baslik = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 204, 255));

        label_username.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        label_username.setText("Kullanici Adi : ");

        text_username.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        text_username.setPreferredSize(new java.awt.Dimension(69, 39));
        text_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_usernameActionPerformed(evt);
            }
        });
        text_username.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                text_usernameKeyPressed(evt);
            }
        });

        label_password.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        label_password.setText("Sifre : ");

        Btn_Menu.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        Btn_Menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/java/icons/home.png"))); // NOI18N
        Btn_Menu.setText("Ana Ekrana Git");
        Btn_Menu.setIconTextGap(10);
        Btn_Menu.setPreferredSize(new java.awt.Dimension(180, 51));
        Btn_Menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_MenuActionPerformed(evt);
            }
        });

        password.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        password.setMinimumSize(new java.awt.Dimension(39, 69));
        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });
        password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passwordKeyPressed(evt);
            }
        });

        Btn_Giris.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        Btn_Giris.setIcon(new javax.swing.ImageIcon(getClass().getResource("/java/icons/login.png"))); // NOI18N
        Btn_Giris.setText(" Giris Yap");
        Btn_Giris.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_GirisActionPerformed(evt);
            }
        });

        label_baslik.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        label_baslik.setForeground(new java.awt.Color(44, 29, 111));
        label_baslik.setText("Yonetici Girisi");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(label_baslik)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(label_password)
                            .addComponent(label_username))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(text_username, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(142, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(Btn_Menu, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(150, 150, 150))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(Btn_Giris, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(178, 178, 178))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(label_baslik)
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_username)
                    .addComponent(text_username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_password)
                    .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(Btn_Giris, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(Btn_Menu, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void text_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_usernameActionPerformed

    private void text_usernameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_text_usernameKeyPressed

    }//GEN-LAST:event_text_usernameKeyPressed

    private void Btn_MenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_MenuActionPerformed
        this.dispose();
        new MainWindow().setVisible(true);
    }//GEN-LAST:event_Btn_MenuActionPerformed

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordActionPerformed

    private void Btn_GirisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_GirisActionPerformed
        if (checkInputs()) {
            Connection conn = null;
            try {
                conn = getConnection();
            } catch (SQLException | ClassNotFoundException ex) {
                Logger.getLogger(AdminLoginWindow.class.getName()).log(Level.SEVERE, null, ex);
            }
            PreparedStatement ps;
            ResultSet rs;
            String query = "SELECT * FROM `BX-Admin` WHERE `Username` = ? AND Password = ?;";
            String pass = String.valueOf(password.getPassword());
            try {
                ps = conn.prepareStatement(query);
                ps.setString(1, text_username.getText());
                ps.setString(2, pass);
                rs = ps.executeQuery();
                if (rs.next()) {
                    this.dispose();
                    new AdminWindow(text_username.getText()).setVisible(true);
                } else {
                    JOptionPane.showMessageDialog(null, "<html><b>Kullanici adi veya sifreniz hatalidir.</b></html>");
                }
            } catch (SQLException ex) {
                Logger.getLogger(AdminLoginWindow.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, "<html><b>Yonetici girisi islemi sirasinda hata olustu.</b></html>");
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(AdminLoginWindow.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(null, "<html><b>Bir ya da daha fazla alani bos biraktiniz.</b></html>");
        }
    }//GEN-LAST:event_Btn_GirisActionPerformed

    private void passwordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordKeyPressed
        int key = evt.getKeyCode();
        if (key == KeyEvent.VK_ENTER) {
            if (checkInputs()) {
                Connection conn = null;
                try {
                    conn = getConnection();
                } catch (SQLException | ClassNotFoundException ex) {
                    Logger.getLogger(AdminLoginWindow.class.getName()).log(Level.SEVERE, null, ex);
                }
                PreparedStatement ps;
                ResultSet rs;
                String query = "SELECT * FROM `BX-Admin` WHERE `Username` = ? AND Password = ?;";
                String pass = String.valueOf(password.getPassword());
                try {
                    ps = conn.prepareStatement(query);
                    ps.setString(1, text_username.getText());
                    ps.setString(2, pass);
                    rs = ps.executeQuery();
                    if (rs.next()) {
                        this.dispose();
                        new AdminWindow(text_username.getText()).setVisible(true);
                    } else {
                        JOptionPane.showMessageDialog(null, "<html><b>Kullanici adi veya sifreniz hatalidir.</b></html>");
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(AdminLoginWindow.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(null, "<html><b>Yonetici girisi islemi sirasinda hata olustu.</b></html>");
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(AdminLoginWindow.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                JOptionPane.showMessageDialog(null, "<html><b>Bir ya da daha fazla alani bos biraktiniz.</b></html>");
            }
        }
    }//GEN-LAST:event_passwordKeyPressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Giris;
    private javax.swing.JButton Btn_Menu;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel label_baslik;
    private javax.swing.JLabel label_password;
    private javax.swing.JLabel label_username;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField text_username;
    // End of variables declaration//GEN-END:variables
}
