
package main;

import com.sun.glass.events.KeyEvent;
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 * Yazilim Laboratuvari I Proje 1
 * @author Oguz Aktas
 */
public class SignupWindow extends javax.swing.JFrame {

    /**
     * Creates new form SignupWindow
     * @throws java.sql.SQLException
     * @throws java.lang.ClassNotFoundException
     */
    public SignupWindow() throws SQLException, ClassNotFoundException {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Kitap Okuma ve Oneri Sistemi");
        showMinID();
    }
    
    public Connection getConnection() throws SQLException, ClassNotFoundException {
        Connection conn;
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/book_crossing?useSSL=false", "root", "123456");
            return conn;
        } catch (SQLException ex) {
            Logger.getLogger(SignupWindow.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "<html><b>Veritabanina baglanti saglanamadi</b></html>");
        }
        return null;
    }
    
    public final void showMinID() throws SQLException, ClassNotFoundException {
        Connection conn = getConnection();
        String query = "SELECT `User-ID` FROM `BX-Users` ORDER BY `User-ID` DESC LIMIT 1;";
        Statement st;
        ResultSet rs;
        int minid = 1;
        try {
            st = conn.createStatement();
            rs = st.executeQuery(query);
            if (rs.next()) {
                minid = rs.getInt(1) + 1;
            }
        } catch (SQLException ex) {
            Logger.getLogger(SignupWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
        text_idenkucuk.setText(String.valueOf(minid));
        text_idenkucuk.setEditable(false);
    }
    
        public boolean checkInputs() {
        if (text_id.getText().trim().isEmpty() || password.getText().trim().isEmpty() || password_tekrar.getText().trim().isEmpty() || text_konum.getText().trim().isEmpty() || text_yas.getText().trim().isEmpty()) {
            return false;
        } else {
            return true;
        }
    }    
    
    public boolean checkID(String id) throws SQLException, ClassNotFoundException {
        Connection conn = getConnection();
        String query = "SELECT * FROM `BX-Users` WHERE `User-ID` = '" + id + "';";
        Statement st;
        ResultSet rs;
        boolean used = false;
        try {
            st = conn.createStatement();
            rs = st.executeQuery(query);
            if (rs.next()) {
                used = true;
            }
        } catch (SQLException ex) {
            Logger.getLogger(SignupWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
        return used;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        label_id = new javax.swing.JLabel();
        text_id = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        label_sifre = new javax.swing.JLabel();
        Btn_Kayit = new javax.swing.JButton();
        Btn_Menu = new javax.swing.JButton();
        label_sifretekrar = new javax.swing.JLabel();
        password_tekrar = new javax.swing.JPasswordField();
        label_idenkucuk = new javax.swing.JLabel();
        text_idenkucuk = new javax.swing.JTextField();
        label_girisyap = new javax.swing.JLabel();
        label_konum = new javax.swing.JLabel();
        label_yas = new javax.swing.JLabel();
        text_konum = new javax.swing.JTextField();
        text_yas = new javax.swing.JTextField();
        label_baslik = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 204, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(521, 432));

        label_id.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        label_id.setText("Kullanici ID : ");

        text_id.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        text_id.setPreferredSize(new java.awt.Dimension(69, 39));
        text_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_idActionPerformed(evt);
            }
        });
        text_id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                text_idKeyPressed(evt);
            }
        });

        password.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        password.setMinimumSize(new java.awt.Dimension(39, 69));
        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });

        label_sifre.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        label_sifre.setText("Sifre : ");

        Btn_Kayit.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        Btn_Kayit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/java/icons/signup.png"))); // NOI18N
        Btn_Kayit.setText("Uye Ol");
        Btn_Kayit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_KayitActionPerformed(evt);
            }
        });
        Btn_Kayit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Btn_KayitKeyPressed(evt);
            }
        });

        Btn_Menu.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        Btn_Menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/java/icons/home.png"))); // NOI18N
        Btn_Menu.setText("Ana Ekrana Git");
        Btn_Menu.setIconTextGap(10);
        Btn_Menu.setPreferredSize(new java.awt.Dimension(180, 51));
        Btn_Menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_MenuActionPerformed(evt);
            }
        });

        label_sifretekrar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        label_sifretekrar.setText("Sifre Tekrar : ");

        password_tekrar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        password_tekrar.setMinimumSize(new java.awt.Dimension(39, 69));
        password_tekrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                password_tekrarActionPerformed(evt);
            }
        });

        label_idenkucuk.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        label_idenkucuk.setText("Kullanilabilir durumda olan en kucuk ID numarasi : ");

        text_idenkucuk.setBackground(new java.awt.Color(51, 204, 255));
        text_idenkucuk.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        text_idenkucuk.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        text_idenkucuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_idenkucukActionPerformed(evt);
            }
        });

        label_girisyap.setFont(new java.awt.Font("Tahoma", 2, 20)); // NOI18N
        label_girisyap.setText("Giris yapmak icin tiklayin");
        label_girisyap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_girisyapMouseClicked(evt);
            }
        });

        label_konum.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        label_konum.setText("Konum (Il, Eyalet, Ulke) : ");

        label_yas.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        label_yas.setText("Yas : ");

        text_konum.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        text_konum.setPreferredSize(new java.awt.Dimension(69, 39));
        text_konum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_konumActionPerformed(evt);
            }
        });

        text_yas.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        text_yas.setPreferredSize(new java.awt.Dimension(69, 39));
        text_yas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_yasActionPerformed(evt);
            }
        });
        text_yas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                text_yasKeyPressed(evt);
            }
        });

        label_baslik.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        label_baslik.setForeground(new java.awt.Color(44, 29, 111));
        label_baslik.setText("Uye Ol");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(label_idenkucuk)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(text_idenkucuk, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(label_id)
                                .addGap(18, 18, 18)
                                .addComponent(text_id, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(64, 64, 64))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(264, 264, 264)
                        .addComponent(label_baslik)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(label_sifretekrar)
                            .addComponent(label_konum)
                            .addComponent(label_yas)
                            .addComponent(label_sifre))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(password_tekrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(text_konum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(text_yas, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(178, 178, 178))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_girisyap, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(Btn_Kayit, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30))
                            .addComponent(Btn_Menu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(204, 204, 204))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addComponent(label_baslik)
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_id))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_idenkucuk)
                    .addComponent(text_idenkucuk, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_sifre)
                    .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_sifretekrar)
                    .addComponent(password_tekrar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_konum)
                    .addComponent(text_konum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_yas)
                    .addComponent(text_yas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(Btn_Kayit)
                .addGap(18, 18, 18)
                .addComponent(label_girisyap, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(Btn_Menu, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 658, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 770, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void text_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_idActionPerformed

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordActionPerformed

    private void Btn_KayitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_KayitActionPerformed
        if (checkInputs()) {
            try {
                if (checkID(text_id.getText())) {
                    JOptionPane.showMessageDialog(null, "<html><b>Bu ID numarasi kullanilmaktadir.</b></html>");
                } else {
                    if (password.getText().equals(password_tekrar.getText())) {
                        this.dispose();
                        new UserConfirmWindow(text_id.getText(), text_konum.getText(), text_yas.getText(), password.getText()).setVisible(true);
                        // JOptionPane.showMessageDialog(null, "<html><b>Son olarak uyeliginizin tamamlanmasi icin en az 10 kitap oylamaniz gerekmektedir.</b></html>"); 
                    } else {
                        JOptionPane.showMessageDialog(null, "<html><b>Girdiginiz sifreler birbiriyle uyusmamaktadir.</b></html>");
                    }
                }
            } catch (SQLException | ClassNotFoundException ex) {
                Logger.getLogger(SignupWindow.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(null, "<html><b>Bir ya da daha fazla alani bos biraktiniz.</b></html>");
        }
    }//GEN-LAST:event_Btn_KayitActionPerformed

    private void Btn_MenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_MenuActionPerformed
        this.dispose();
        new MainWindow().setVisible(true);
    }//GEN-LAST:event_Btn_MenuActionPerformed

    private void password_tekrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_password_tekrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_password_tekrarActionPerformed

    private void label_girisyapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_girisyapMouseClicked
        this.dispose();
        new LoginWindow().setVisible(true);
    }//GEN-LAST:event_label_girisyapMouseClicked

    private void text_konumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_konumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_konumActionPerformed

    private void text_yasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_yasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_yasActionPerformed

    private void text_idKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_text_idKeyPressed
        text_id.setEditable(true);
        int key = evt.getKeyCode();
        if ((key >= evt.VK_0 && key <= evt.VK_9) || (key >= evt.VK_NUMPAD0 && key <= evt.VK_NUMPAD9) || key == KeyEvent.VK_BACKSPACE || (key == KeyEvent.VK_ALT || key == KeyEvent.VK_TAB || key == KeyEvent.VK_ENTER || key == KeyEvent.VK_LEFT || key == KeyEvent.VK_RIGHT)) {
            text_id.setEditable(true);
            text_id.setBackground(Color.YELLOW);
        } else {
            text_id.setEditable(false);
            text_id.setBackground(Color.RED);
        }
    }//GEN-LAST:event_text_idKeyPressed

    private void text_yasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_text_yasKeyPressed
        text_yas.setEditable(true);
        int key = evt.getKeyCode();
        if ((key >= evt.VK_0 && key <= evt.VK_9) || (key >= evt.VK_NUMPAD0 && key <= evt.VK_NUMPAD9) || key == KeyEvent.VK_BACKSPACE || (key == KeyEvent.VK_ALT || key == KeyEvent.VK_TAB || key == KeyEvent.VK_LEFT || key == KeyEvent.VK_RIGHT)) {
            text_yas.setEditable(true);
            text_yas.setBackground(Color.YELLOW);
        } else if (key == KeyEvent.VK_ENTER) {
            if (checkInputs()) {
                try {
                    if (checkID(text_id.getText())) {
                        JOptionPane.showMessageDialog(null, "<html><b>Bu ID numarasi kullanilmaktadir.</b></html>");
                    } else {
                        if (password.getText().equals(password_tekrar.getText())) {
                            this.dispose();
                            new UserConfirmWindow(text_id.getText(), text_konum.getText(), text_yas.getText(), password.getText()).setVisible(true);
                            // JOptionPane.showMessageDialog(null, "<html><b>Son olarak uyeliginizin tamamlanmasi icin en az 10 kitap oylamaniz gerekmektedir.</b></html>");
                        } else {
                            JOptionPane.showMessageDialog(null, "<html><b>Girdiginiz sifreler birbiriyle uyusmamaktadir.</b></html>");
                        }
                    }
                } catch (SQLException | ClassNotFoundException ex) {
                    Logger.getLogger(SignupWindow.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                JOptionPane.showMessageDialog(null, "<html><b>Bir ya da daha fazla alani bos biraktiniz.</b></html>");
            }
        } else {
            text_yas.setEditable(false);
            text_yas.setBackground(Color.RED);
        }
    }//GEN-LAST:event_text_yasKeyPressed

    private void text_idenkucukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_idenkucukActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_idenkucukActionPerformed

    private void Btn_KayitKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Btn_KayitKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_KayitKeyPressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Kayit;
    private javax.swing.JButton Btn_Menu;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel label_baslik;
    private javax.swing.JLabel label_girisyap;
    private javax.swing.JLabel label_id;
    private javax.swing.JLabel label_idenkucuk;
    private javax.swing.JLabel label_konum;
    private javax.swing.JLabel label_sifre;
    private javax.swing.JLabel label_sifretekrar;
    private javax.swing.JLabel label_yas;
    private javax.swing.JPasswordField password;
    private javax.swing.JPasswordField password_tekrar;
    private javax.swing.JTextField text_id;
    private javax.swing.JTextField text_idenkucuk;
    private javax.swing.JTextField text_konum;
    private javax.swing.JTextField text_yas;
    // End of variables declaration//GEN-END:variables
}
